<?php
use Illuminate\Database\Seeder;
use App\Person;

/**
 * Created by PhpStorm.
 * User: Erina
 * Date: 4/6/2015
 * Time: 12:08 AM
 */

class PersonSeeder extends Seeder {

    public function run() {

        DB::table('people')->delete();
        $girls = array(
            array('id' => '1','firstName' => 'Kokomi','lastName' => 'Shina','firstNameJP' => '心実','lastNameJP' => '椎名','type' => 'COOL','authority' => 'Students','authorityJP' => '学生','year' => '2nd','age' => '17','birthday' => '5/31/2015','horoscope' => 'Gemini','horoscopeJP' => '双子座','bloodType' => 'O','height' => '160','weight' => '48','threeSizes' => 'B83/W58/H85','favoriteSubject' => 'English','favoriteSubjectJP' => '英語','extracurricular' => 'Rhythmic Gymnastics Club','extracurricularJP' => '新体操部','hobbies' => 'Collecting Aromatherapy Candles','hobbiesJP' => 'アロマキャンドル','favoriteFood' => 'Melonpan','favoriteFoodJP' => 'メロンパン','hatedFood' => 'Tuna','hatedFoodJP' => 'ツナ','cv' => 'Satomi Sato','cvJP' => '佐藤聡美'),
            array('id' => '2','firstName' => 'Fumio','lastName' => 'Murakami','firstNameJP' => '文緒','lastNameJP' => '村上','type' => 'COOL','authority' => 'Students','authorityJP' => '学生','year' => '3rd','age' => '18','birthday' => '11/2/2015','horoscope' => 'Scorpio','horoscopeJP' => '蠍座','bloodType' => 'B','height' => '160','weight' => '45','threeSizes' => 'B86/W56/H86','favoriteSubject' => 'Classic Literature','favoriteSubjectJP' => '古典','extracurricular' => 'Library Assistant','extracurricularJP' => '図書委員会','hobbies' => 'Reading','hobbiesJP' => '読書','favoriteFood' => 'Cake','favoriteFoodJP' => 'ケーキ','hatedFood' => 'Liver','hatedFoodJP' => 'レバー','cv' => 'Kaori Nazuka','cvJP' => '名塚佳織'),
            array('id' => '3','firstName' => 'Akane','lastName' => 'Sakurai','firstNameJP' => '明音','lastNameJP' => '櫻井','type' => 'POP','authority' => 'Students','authorityJP' => '学生','year' => '2nd','age' => '17','birthday' => '11/20/2015','horoscope' => 'Scorpio','horoscopeJP' => '蠍座','bloodType' => 'A','height' => '160','weight' => '48','threeSizes' => 'B85/W58/H87','favoriteSubject' => 'Modern Society','favoriteSubjectJP' => '現代社会','extracurricular' => 'School Radio Broadcaster','extracurricularJP' => '放送委員会','hobbies' => 'Tongue Twisters and Collecting Ribbons','hobbiesJP' => '早口言葉/リボンやシュシュ収集','favoriteFood' => 'Melons','favoriteFoodJP' => 'メロン','hatedFood' => 'Dried Plums','hatedFoodJP' => '梅干し','cv' => 'Rina Sato','cvJP' => '佐藤利奈'),
            array('id' => '4','firstName' => 'Chloe','lastName' => 'Lemaire','firstNameJP' => 'クロエ','lastNameJP' => 'ルメール','type' => 'SWEET','authority' => 'Students','authorityJP' => '学生','year' => '3rd','age' => '17','birthday' => '3/8/2015','horoscope' => 'Pisces','horoscopeJP' => '魚座','bloodType' => 'O','height' => '167','weight' => '49','threeSizes' => 'B86/W60/H88','favoriteSubject' => 'Art','favoriteSubjectJP' => '美術','extracurricular' => 'Japanese Culture Research Association','extracurricularJP' => '日本文化研究会','hobbies' => 'Traveling to Various Temples and Shrines Across Japan','hobbiesJP' => '寺社仏閣/旅行','favoriteFood' => 'Sushi','favoriteFoodJP' => 'お寿司','hatedFood' => 'Pickled Vegetables','hatedFoodJP' => '奈良漬','cv' => 'Sakura Tange','cvJP' => '丹下桜'),
            array('id' => '5','firstName' => 'Erena','lastName' => 'Mochizuki','firstNameJP' => 'エレナ','lastNameJP' => '望月','type' => 'SWEET','authority' => 'Students','authorityJP' => '学生','year' => '3rd','age' => '18','birthday' => '5/25/2015','horoscope' => 'Gemini','horoscopeJP' => '双子座','bloodType' => 'B','height' => '165','weight' => '48','threeSizes' => 'B88/W55/H88','favoriteSubject' => 'English','favoriteSubjectJP' => '英語','extracurricular' => 'Phtography Club','extracurricularJP' => '写真部','hobbies' => 'Taking Self Portraits and Fantasizing','hobbiesJP' => 'セルフポートレート/妄想/女の子','favoriteFood' => 'Chocolate','favoriteFoodJP' => 'チョコレート','hatedFood' => 'Daifuku','hatedFoodJP' => '大福','cv' => 'Hitomi Harada','cvJP' => '原田ひとみ'),
            array('id' => '6','firstName' => 'Ichigo','lastName' => 'Kohinata','firstNameJP' => 'いちご','lastNameJP' => '小日向','type' => 'SWEET','authority' => 'Students','authorityJP' => '学生','year' => '1st','age' => '15','birthday' => '1/5/2015','horoscope' => 'Capricorn','horoscopeJP' => '山羊座','bloodType' => 'O','height' => '146','weight' => '45','threeSizes' => 'B83/W57/H82','favoriteSubject' => 'Art','favoriteSubjectJP' => '美術','extracurricular' => 'Art Club','extracurricularJP' => '美術部','hobbies' => 'Making Decorative Fruit and Touring Museums','hobbiesJP' => '美術館めぐり/フルーツデコ','favoriteFood' => 'Strawberries and Peaches','favoriteFoodJP' => 'イチゴ、桃','hatedFood' => 'Durians','hatedFoodJP' => 'ドリアン','cv' => 'Ayana Taketatsu','cvJP' => '竹達彩奈'),
            array('id' => '7','firstName' => 'Momoko','lastName' => 'Asahina','firstNameJP' => '桃子','lastNameJP' => '朝比奈','type' => 'SWEET','authority' => 'Students','authorityJP' => '学生','year' => '1st','age' => '16','birthday' => '7/19/2015','horoscope' => 'Cancer','horoscopeJP' => '蟹座','bloodType' => 'O','height' => '145','weight' => '44','threeSizes' => 'B75/W58/H78','favoriteSubject' => 'Music','favoriteSubjectJP' => '音楽','extracurricular' => 'Band Club','extracurricularJP' => '軽音部','hobbies' => 'Collecting Seals and Playing Music','hobbiesJP' => 'シール集め/音楽','favoriteFood' => 'Ramune','favoriteFoodJP' => '笛ラムネ','hatedFood' => 'Bitter Gourds','hatedFoodJP' => 'ゴーヤ','cv' => 'Yui Ogura','cvJP' => '小倉唯'),
            array('id' => '8','firstName' => 'Michiru','lastName' => 'Tomura','firstNameJP' => '美知留','lastNameJP' => '戸村','type' => 'POP','authority' => 'Students','authorityJP' => '学生','year' => '2nd','age' => '16','birthday' => '6/26/2015','horoscope' => 'Cancer','horoscopeJP' => '蟹座','bloodType' => 'B','height' => '162','weight' => '48','threeSizes' => 'B85/W58/H87','favoriteSubject' => 'Home Economics','favoriteSubjectJP' => '家庭科','extracurricular' => 'Going Home Club','extracurricularJP' => '帰宅部','hobbies' => 'Making Costumes and Impersonating People','hobbiesJP' => 'コス衣装制作/モノマネ','favoriteFood' => 'Ramen','favoriteFoodJP' => '塩らーめん','hatedFood' => 'Green Juice','hatedFoodJP' => '青汁','cv' => 'Asumi Kana','cvJP' => '阿澄佳奈'),
            array('id' => '9','firstName' => 'Nonoka','lastName' => 'Sasahara','firstNameJP' => '野々花','lastNameJP' => '笹原','type' => 'SWEET','authority' => 'Students','authorityJP' => '学生','year' => '3rd','age' => '18','birthday' => '9/13/2015','horoscope' => 'Virgo','horoscopeJP' => '乙女座','bloodType' => 'O','height' => '164','weight' => '47','threeSizes' => 'B90/W58/H89','favoriteSubject' => 'English','favoriteSubjectJP' => '英語','extracurricular' => 'Pottery Club','extracurricularJP' => '陶芸部','hobbies' => 'Bird Watching and Bath Salt Collecting','hobbiesJP' => '小鳥/入浴剤集め','favoriteFood' => 'French Toast','favoriteFoodJP' => 'フレンチトースト','hatedFood' => 'Oysters','hatedFoodJP' => '牡蠣','cv' => 'Haruka Tomatsu','cvJP' => '戸松遥'),
            array('id' => '10','firstName' => 'Remi','lastName' => 'Tamai','firstNameJP' => '麗巳','lastNameJP' => '玉井','type' => 'POP','authority' => 'Students','authorityJP' => '学生','year' => '3rd','age' => '17','birthday' => '1/31/2015','horoscope' => 'Aquarius','horoscopeJP' => '水瓶座','bloodType' => 'O','height' => '163','weight' => '48','threeSizes' => 'B76/W56/H78','favoriteSubject' => 'None','favoriteSubjectJP' => 'なし','extracurricular' => 'Golf Club','extracurricularJP' => 'ゴルフ部','hobbies' => 'Playing Golf','hobbiesJP' => 'ゴルフ','favoriteFood' => 'Dumplings','favoriteFoodJP' => 'シュウマイ','hatedFood' => 'Soybean Flour','hatedFoodJP' => 'きなこ','cv' => 'Noriko Shitaya','cvJP' => '下屋則子'),
            array('id' => '11','firstName' => 'Koruri','lastName' => 'Tokitani','firstNameJP' => '小瑠璃','lastNameJP' => '時谷','type' => 'POP','authority' => 'Students','authorityJP' => '学生','year' => '3rd','age' => '17','birthday' => '11/29/2015','horoscope' => 'Sagittarius','horoscopeJP' => '射手座','bloodType' => 'B','height' => '148','weight' => '43','threeSizes' => 'B73/W57/H78','favoriteSubject' => 'Home Economics','favoriteSubjectJP' => '家庭科','extracurricular' => 'Handicrafts Club','extracurricularJP' => '手芸部','hobbies' => 'Designing Fashion, Especially Dresses','hobbiesJP' => '服飾デザイン/着せ替え（人間の）','favoriteFood' => 'Madeleine','favoriteFoodJP' => 'マドレーヌ','hatedFood' => 'Pineapple, Pilaf, Raisins, and Sweet and Sour Pork','hatedFoodJP' => '酢豚のパイナップル ピラフのレーズン','cv' => 'Yukari Tamura','cvJP' => '田村ゆかり'),
            array('id' => '12','firstName' => 'Rui','lastName' => 'Kamijo','firstNameJP' => 'るい','lastNameJP' => '上条','type' => 'COOL','authority' => 'Students','authorityJP' => '学生','year' => '2nd','age' => '17','birthday' => '5/2/2015','horoscope' => 'Taurus','horoscopeJP' => '牡牛座','bloodType' => 'A','height' => '158','weight' => '44','threeSizes' => 'B70/W53/H73','favoriteSubject' => 'English','favoriteSubjectJP' => '英語','extracurricular' => 'Archery Club','extracurricularJP' => '弓道部','hobbies' => 'Solving Wire Puzzles','hobbiesJP' => '知恵の輪','favoriteFood' => 'Takoyaki','favoriteFoodJP' => 'たこ焼き','hatedFood' => 'Jasmine Tea','hatedFoodJP' => 'ジャスミン茶','cv' => 'Yui Watanabe','cvJP' => '渡邉優衣'),
            array('id' => '13','firstName' => 'Matsuri','lastName' => 'Kagami','firstNameJP' => '茉莉','lastNameJP' => '加賀美','type' => 'SWEET','authority' => 'Students','authorityJP' => '学生','year' => '2nd','age' => '17','birthday' => '7/1/2015','horoscope' => 'Cancer','horoscopeJP' => '蟹座','bloodType' => 'AB','height' => '153','weight' => '44','threeSizes' => 'B73/W53/H78','favoriteSubject' => 'English','favoriteSubjectJP' => '英語','extracurricular' => 'Tennis Club','extracurricularJP' => 'テニス部','hobbies' => 'Playing Tennis, Drawing, and Collecting Fairy Tale Books','hobbiesJP' => 'テニス（表向き）/童話・絵本の収集、描くこと','favoriteFood' => 'Pudding','favoriteFoodJP' => 'プリン','hatedFood' => 'Green Onions','hatedFoodJP' => 'ネギ','cv' => 'Rie Kugimiya','cvJP' => '釘宮理恵')
        );

        foreach($girls as $girl) {
            Person::create($girl);
        }

    }
}